[package]
authors = ["Dave Allie <dave@daveallie.com>", "Noah Hüsser <yatekii@yatekii.ch>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "BSP for the Pitaya Go"
keywords = ["arm", "cortex-m", "nrf52", "hal"]
license = "MIT"
name = "pitaya-go-bsp"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = "0.7"
embedded-hal = "0.2"
nrf52840-hal = "0.13.0"

[dev-dependencies]
cortex-m-rt = ">=0.6, <0.8"
nb = "1.0.0"
panic-halt = "0.2.0"
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
rtt-target = { version = "0.3.1", features = ["cortex-m"] }

[features]
rt = ["nrf52840-hal/rt"]
default = ["rt"]
